version: '3'
services:
  php:
    container_name: test_service-php
    image: amocrmapi-php:latest
    ports:
      - '9002:9000'
    volumes:
      - ../:/var/www/test-service
      - ./logs/symfony:/var/www/test-service/var/logs
    networks:
      - common_network
  nginx:
    container_name: test_service-nginx
    image: nginx
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - ../:/var/www/test-service
      - ./logs/nginx/:/var/log/nginx
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - common_network
#      - proxy_read_timeout 1800;
#      - proxy_connect_timeout 1800;
#      - proxy_send_timeout 1800;
#      - send_timeout 1800;
  redis:
    container_name: test_service-redis
    image: redis
    depends_on:
      - nginx
    networks:
      - common_network
networks:
  common_network:
    driver: bridge

